name: DevOCGen-workshop
channels:
  - conda-forge
dependencies:
  - python=3.12.0
  - pip
  - jupyterlab
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pip:
    - tsinfer
    - tsdate
    - msprime
    - tskit
    - pyslim
    - seaborn
    - scipy
    - ipywidgets
